name: smart360
description: A home automation smart application.
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  awesome_circular_chart: ^1.0.0
  build_runner: ^2.4.8
  cached_network_image: ^3.2.0
  cloud_firestore: ^4.13.5
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  dio: ^5.4.1
  dotted_border: ^2.0.0+2
  firebase_auth: ^4.15.3
  firebase_core: ^2.24.2
  firebase_database: ^10.3.8
  firebase_storage: ^11.6.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  flutter_screenutil: ^5.3.1
  flutter_svg: ^2.0.7
  font_awesome_flutter: ^10.4.0
  geocoding: ^2.2.1+1
  geolocator: ^11.0.0
  get_it: ^7.2.0
  google_fonts: ^4.0.4
  image_picker: ^0.8.4+11
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  lottie: ^2.4.0
  provider: ^6.0.2
  shared_preferences: ^2.2.2
  sleek_circular_slider: ^2.0.1
  sliding_up_panel: ^2.0.0+1
  syncfusion_flutter_charts: ^22.1.34
  table_calendar: ^3.0.4
  smooth_page_indicator: ^1.1.0

dev_dependencies:
  flutter_lints: ^2.0.1

  flutter_native_splash: ^2.3.1
  flutter_test:
    sdk: flutter

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/favourite.png
  android: true
  ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/favourite.png
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - assets/images/weather/
    - assets/images/settings/
    - assets/icons/svg/
    - assets/Lottie/
    - assets/icons/menu_icons/
    - assets/icons/device_icons/

  fonts:
    - family: "Noto Sans"
      fonts:
        - asset: "assets/fonts/NotoSans-Bold.ttf"
          style: "normal"
        - asset: "assets/fonts/NotoSans-Regular.ttf"
          style: "normal"
    - family: "Poppins"
      fonts:
        - asset: "assets/fonts/Poppins-700.ttf"
          style: "normal"
          weight: 700
    - family: ABeeZee
      fonts:
        - asset: assets/fonts/ABeeZee-Italic.ttf
          style: italic
        - asset: assets/fonts/ABeeZee-Regular.ttf
          style: normal
    - family: Lexend
      fonts:
        - asset: assets/fonts/Lexend-Medium.ttf
          weight: 500
        - asset: assets/fonts/Lexend-ExtraLight.ttf
          weight: 200
